### ISSUE TITLE
[Enhancement] Applications Data: Show decoded fields from payload

### ISSUE THREAD

**Issue by cBashTN** [async-la/ttn-mobile#202]
In https://console.thethingsnetwork.org/applications/{myApplicationName}/data I can see the fields that are decoded from my payload format.  [https://i.imgur.com/JzF9R2O.png](https://i.imgur.com/JzF9R2O.png)

It would be nice seeing this decoded fields in the app, too.

**Comment by christopherdro** [comment]
This was recently pushed live and should be updated on your device without having to download/upgrade the app from the store.

You can double check by checking the version number in the profile tab of the app. It should read 1.26.1

**Comment by cBashTN** [comment]
I tested it and I can verify it works! Well done!
